package javaMail;

public class EmailTemplate {
	public static String getForgotPasswordTemplate(String password, String link) {
		return "<!doctype html>\r\n"
				+ "<html lang=\"en\">\r\n"
				+ "  <head>\r\n"
				+ "    <meta charset=\"utf-8\">\r\n"
				+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
				+ "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n"
				+ "    <title>Email</title>\r\n"
				+ "    <link\r\n"
				+ "	href=\"https://fonts.googleapis.com/css?family=Archivo+Narrow:300,400,700%7CMontserrat:300,400,500,600,700,800,900\"\r\n"
				+ "	rel=\"stylesheet\">\r\n"
				+ "    <style media=\"all\" type=\"text/css\">\r\n"
				+ "    \r\n"
				+ "@media all {\r\n"
				+ "  .btn-primary table td:hover {\r\n"
				+ "    background-color: #4fce95 !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  .btn-primary a:hover {\r\n"
				+ "    background-color: #4fce95 !important;\r\n"
				+ "    border-color: #4fce95 !important;\r\n"
				+ "  }\r\n"
				+ "}\r\n"
				+ "@media only screen and (max-width: 640px) {\r\n"
				+ "  .main p,\r\n"
				+ ".main td,\r\n"
				+ ".main span {\r\n"
				+ "    font-size: 16px !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  .wrapper {\r\n"
				+ "    padding: 8px !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  .content {\r\n"
				+ "    padding: 0 !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  .container {\r\n"
				+ "    padding: 0 !important;\r\n"
				+ "    padding-top: 8px !important;\r\n"
				+ "    width: 100% !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  .main {\r\n"
				+ "    border-left-width: 0 !important;\r\n"
				+ "    border-radius: 0 !important;\r\n"
				+ "    border-right-width: 0 !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  .btn table {\r\n"
				+ "    max-width: 100% !important;\r\n"
				+ "    width: 100% !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  .btn a {\r\n"
				+ "    font-size: 16px !important;\r\n"
				+ "    max-width: 100% !important;\r\n"
				+ "    width: 100% !important;\r\n"
				+ "  }\r\n"
				+ "}\r\n"
				+ "@media all {\r\n"
				+ "  .ExternalClass {\r\n"
				+ "    width: 100%;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  .ExternalClass,\r\n"
				+ ".ExternalClass p,\r\n"
				+ ".ExternalClass span,\r\n"
				+ ".ExternalClass font,\r\n"
				+ ".ExternalClass td,\r\n"
				+ ".ExternalClass div {\r\n"
				+ "    line-height: 100%;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  .apple-link a {\r\n"
				+ "    color: inherit !important;\r\n"
				+ "    font-family: inherit !important;\r\n"
				+ "    font-size: inherit !important;\r\n"
				+ "    font-weight: inherit !important;\r\n"
				+ "    line-height: inherit !important;\r\n"
				+ "    text-decoration: none !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  #MessageViewBody a {\r\n"
				+ "    color: inherit;\r\n"
				+ "    text-decoration: none;\r\n"
				+ "    font-size: inherit;\r\n"
				+ "    font-family: inherit;\r\n"
				+ "    font-weight: inherit;\r\n"
				+ "    line-height: inherit;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  body {\r\n"
				+ "    font-family: \"Helvetica Neue\",Helvetica,Arial,sans-serif;\r\n"
				+ "  }\r\n"
				+ "}\r\n"
				+ "</style>\r\n"
				+ "  </head>\r\n"
				+ "  <body style=\"font-family: Archivo Narrow; -webkit-font-smoothing: antialiased; font-size: 16px; line-height: 1.3; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; background-color: #f4f5f6; margin: 0; padding: 0;\">\r\n"
				+ "    <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"body\" style=\"border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #f4f5f6; width: 100%;\" width=\"100%\" bgcolor=\"#f4f5f6\">\r\n"
				+ "      <tr>\r\n"
				+ "        <td style=\"font-family: Archivo Narrow; font-size: 16px; vertical-align: top;\" valign=\"top\">&nbsp;</td>\r\n"
				+ "        <td class=\"container\" style=\"font-family: Archivo Narrow; font-size: 16px; vertical-align: top; max-width: 600px; padding: 0; padding-top: 24px; width: 600px; margin: 0 auto;\" width=\"600\" valign=\"top\">\r\n"
				+ "          <div class=\"content\" style=\"box-sizing: border-box; display: block; margin: 0 auto; max-width: 600px; padding: 0;\">\r\n"
				+ "\r\n"
				+ "            <!-- START CENTERED WHITE CONTAINER -->\r\n"
				+ "            <span class=\"preheader\" style=\"color: transparent; display: none; height: 0; max-height: 0; max-width: 0; opacity: 0; overflow: hidden; mso-hide: all; visibility: hidden; width: 0;\">This is preheader text. Some clients will show this text as a preview.</span>\r\n"
				+ "            <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"main\" style=\"border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; background: #ffffff; border: 1px solid #eaebed; border-radius: 16px; width: 100%;\" width=\"100%\">\r\n"
				+ "\r\n"
				+ "              <!-- START MAIN CONTENT AREA -->\r\n"
				+ "              <tr>\r\n"
				+ "                <td class=\"wrapper\" style=\"font-family: Archivo Narrow; font-size: 16px; vertical-align: top; box-sizing: border-box; padding: 24px;\" valign=\"top\">\r\n"
				+ "                  <p style=\"text-align: center;\">                  <img style=\"margin: 0; margin-bottom: 16px;\" src=\"https://uploads.commoninja.com/searchengine/wordpress/sapo-feed.png\"/>\r\n"
				+ "                  </p>\r\n"
				+ "                  <h1  style=\"text-align: center; font-family: Archivo Narrow; font-weight: normal; margin: 0; margin-bottom: 16px;\">Lấy lại mật khẩu</h1>\r\n"
				+ "                  \r\n"
				+ "                  <p style=\"font-family: Archivo Narrow; font-size: 16px; font-weight: normal;text-align: center; margin: 0; margin-bottom: 16px;\">Mật khẩu của bạn là: <h2 style=\"color:red; text-align: center;\">"
				+ "" + password
				+ "</h2></p>\r\n"
				+ "                  <p style=\"text-align: center;\">                  <a href=\""
				+ "" + link
				+ "\" target=\"_blank\" style=\"border: solid 2px #2AC37D; border-radius: 4px; box-sizing: border-box; cursor: pointer; display: inline-block; font-size: 16px; text-align: center; font-weight: bold; margin: 0; padding: 12px 24px; text-decoration: none; text-transform: capitalize; background-color: #2AC37D; border-color: #2AC37D; color: #ffffff;\">Đến trang đăng nhập</a>\r\n"
				+ "                  </p>\r\n"
				+ "                  <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"btn btn-primary\" style=\"border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; box-sizing: border-box; width: 100%; min-width: 100%;\" width=\"100%\">\r\n"
				+ "\r\n"
				+ "                    <tbody>\r\n"
				+ "                      <tr>\r\n"
				+ "                        <td align=\"left\" style=\"font-family: Archivo Narrow; font-size: 16px; vertical-align: top; padding-bottom: 16px;\" valign=\"top\">\r\n"
				+ "                          <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: auto;\">\r\n"
				+ "                            <tbody>\r\n"
				+ "                              <tr>\r\n"
				+ "                                <td style=\"font-family: Archivo Narrow; font-size: 16px; vertical-align: top; border-radius: 4px; text-align: center; background-color: #0867ec;\" valign=\"top\" align=\"center\" bgcolor=\"#0867ec\">  </td>\r\n"
				+ "                              </tr>\r\n"
				+ "                            </tbody>\r\n"
				+ "                          </table>\r\n"
				+ "                        </td>\r\n"
				+ "                      </tr>\r\n"
				+ "                    </tbody>\r\n"
				+ "                  </table>\r\n"
				+ "                  <p style=\"text-align: center;font-family: Archivo Narrow; font-size: 16px; font-weight: normal; margin: 0; margin-bottom: 16px;\">Ngoài ra, bạn có bất cứ câu hỏi nào cần được hỗ trợ, hãy liên hệ theo số hotline: <a>0111111111</a> hoặc email: <a>cskh@sapo.com</a>. Đội chăm sóc khách hàng sẽ giải đáp thắc mắc một cách nhanh nhất.</p>\r\n"
				+ "                  <p style=\"text-align: center;font-family: Archivo Narrow; font-size: 16px; font-weight: normal; margin: 0; margin-bottom: 16px;\">Cảm ơn bạn đã tin tưởng lựa chọn SAPO STORE</p>\r\n"
				+ "                  <p style=\"text-align: center;font-family: Archivo Narrow; font-size: 16px; font-weight: normal; margin: 0; margin-bottom: 16px;\">Trân trọng!</p>\r\n"
				+ "                </td>\r\n"
				+ "              </tr>\r\n"
				+ "\r\n"
				+ "              <!-- END MAIN CONTENT AREA -->\r\n"
				+ "              </table>\r\n"
				+ "\r\n"
				+ "            <!-- START FOOTER -->\r\n"
				+ "            <div class=\"footer\" style=\"clear: both; padding-top: 24px; text-align: center; width: 100%;\">\r\n"
				+ "              <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;\" width=\"100%\">\r\n"
				+ "                <tr>\r\n"
				+ "                  <td class=\"content-block\" style=\"font-family: Archivo Narrow; vertical-align: top; color: #9a9ea6; font-size: 16px; text-align: center;\" valign=\"top\" align=\"center\">\r\n"
				+ "                    <span class=\"apple-link\" style=\"color: #9a9ea6; font-size: 16px; text-align: center;\">87-89 Hồ Văn Huê, P9, Q.Phú Nhuận, TP.HCM</span>\r\n"
				+ "                    <br> Chăm sóc khách hàng: <a href=\"#\" style=\"text-decoration: underline; color: #9a9ea6; font-size: 16px; text-align: center;\"> cskh1@sapostore.com</a>.\r\n"
				+ "                  </td>\r\n"
				+ "                </tr>\r\n"
				+ "                <tr>\r\n"
				+ "                  <td class=\"content-block powered-by\" style=\"font-family: Archivo Narrow; vertical-align: top; color: #9a9ea6; font-size: 16px; text-align: center;\" valign=\"top\" align=\"center\">\r\n"
				+ "                    Bản quyền thuộc về <a href=\"#\" style=\"color: #9a9ea6; font-size: 16px; text-align: center; text-decoration: none;\">@ ABCXYZ123</a>\r\n"
				+ "                  </td>\r\n"
				+ "                </tr>\r\n"
				+ "              </table>\r\n"
				+ "            </div>\r\n"
				+ "          </div>\r\n"
				+ "        </td>\r\n"
				+ "        <td style=\"font-family: Archivo Narrow; font-size: 16px; vertical-align: top;\" valign=\"top\">&nbsp;</td>\r\n"
				+ "      </tr>\r\n"
				+ "    </table>\r\n"
				+ "  </body>\r\n"
				+ "</html>\r\n"
				+ "";
	}
	
	public static String getSuccessOrderTemplate(String link) {
		return "<!doctype html>\r\n"
				+ "<html lang=\"en\">\r\n"
				+ "  <head>\r\n"
				+ "    <meta charset=\"utf-8\">\r\n"
				+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
				+ "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n"
				+ "    <title>Email</title>\r\n"
				+ "    <link\r\n"
				+ "	href=\"https://fonts.googleapis.com/css?family=Archivo+Narrow:300,400,700%7CMontserrat:300,400,500,600,700,800,900\"\r\n"
				+ "	rel=\"stylesheet\">\r\n"
				+ "    <style media=\"all\" type=\"text/css\">\r\n"
				+ "    \r\n"
				+ "@media all {\r\n"
				+ "  .btn-primary table td:hover {\r\n"
				+ "    background-color: #4fce95 !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  .btn-primary a:hover {\r\n"
				+ "    background-color: #4fce95 !important;\r\n"
				+ "    border-color: #4fce95 !important;\r\n"
				+ "  }\r\n"
				+ "}\r\n"
				+ "@media only screen and (max-width: 640px) {\r\n"
				+ "  .main p,\r\n"
				+ ".main td,\r\n"
				+ ".main span {\r\n"
				+ "    font-size: 16px !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  .wrapper {\r\n"
				+ "    padding: 8px !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  .content {\r\n"
				+ "    padding: 0 !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  .container {\r\n"
				+ "    padding: 0 !important;\r\n"
				+ "    padding-top: 8px !important;\r\n"
				+ "    width: 100% !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  .main {\r\n"
				+ "    border-left-width: 0 !important;\r\n"
				+ "    border-radius: 0 !important;\r\n"
				+ "    border-right-width: 0 !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  .btn table {\r\n"
				+ "    max-width: 100% !important;\r\n"
				+ "    width: 100% !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  .btn a {\r\n"
				+ "    font-size: 16px !important;\r\n"
				+ "    max-width: 100% !important;\r\n"
				+ "    width: 100% !important;\r\n"
				+ "  }\r\n"
				+ "}\r\n"
				+ "@media all {\r\n"
				+ "  .ExternalClass {\r\n"
				+ "    width: 100%;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  .ExternalClass,\r\n"
				+ ".ExternalClass p,\r\n"
				+ ".ExternalClass span,\r\n"
				+ ".ExternalClass font,\r\n"
				+ ".ExternalClass td,\r\n"
				+ ".ExternalClass div {\r\n"
				+ "    line-height: 100%;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  .apple-link a {\r\n"
				+ "    color: inherit !important;\r\n"
				+ "    font-family: inherit !important;\r\n"
				+ "    font-size: inherit !important;\r\n"
				+ "    font-weight: inherit !important;\r\n"
				+ "    line-height: inherit !important;\r\n"
				+ "    text-decoration: none !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  #MessageViewBody a {\r\n"
				+ "    color: inherit;\r\n"
				+ "    text-decoration: none;\r\n"
				+ "    font-size: inherit;\r\n"
				+ "    font-family: inherit;\r\n"
				+ "    font-weight: inherit;\r\n"
				+ "    line-height: inherit;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  body {\r\n"
				+ "    font-family: \"Helvetica Neue\",Helvetica,Arial,sans-serif;\r\n"
				+ "  }\r\n"
				+ "}\r\n"
				+ "</style>\r\n"
				+ "  </head>\r\n"
				+ "  <body style=\"font-family: Archivo Narrow; -webkit-font-smoothing: antialiased; font-size: 16px; line-height: 1.3; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; background-color: #f4f5f6; margin: 0; padding: 0;\">\r\n"
				+ "    <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"body\" style=\"border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #f4f5f6; width: 100%;\" width=\"100%\" bgcolor=\"#f4f5f6\">\r\n"
				+ "      <tr>\r\n"
				+ "        <td style=\"font-family: Archivo Narrow; font-size: 16px; vertical-align: top;\" valign=\"top\">&nbsp;</td>\r\n"
				+ "        <td class=\"container\" style=\"font-family: Archivo Narrow; font-size: 16px; vertical-align: top; max-width: 600px; padding: 0; padding-top: 24px; width: 600px; margin: 0 auto;\" width=\"600\" valign=\"top\">\r\n"
				+ "          <div class=\"content\" style=\"box-sizing: border-box; display: block; margin: 0 auto; max-width: 600px; padding: 0;\">\r\n"
				+ "\r\n"
				+ "            <!-- START CENTERED WHITE CONTAINER -->\r\n"
				+ "            <span class=\"preheader\" style=\"color: transparent; display: none; height: 0; max-height: 0; max-width: 0; opacity: 0; overflow: hidden; mso-hide: all; visibility: hidden; width: 0;\">This is preheader text. Some clients will show this text as a preview.</span>\r\n"
				+ "            <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"main\" style=\"border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; background: #ffffff; border: 1px solid #eaebed; border-radius: 16px; width: 100%;\" width=\"100%\">\r\n"
				+ "\r\n"
				+ "              <!-- START MAIN CONTENT AREA -->\r\n"
				+ "              <tr>\r\n"
				+ "                <td class=\"wrapper\" style=\"font-family: Archivo Narrow; font-size: 16px; vertical-align: top; box-sizing: border-box; padding: 24px;\" valign=\"top\">\r\n"
				+ "                  <p style=\"text-align: center;\">                  <img style=\"margin: 0; margin-bottom: 16px;\" src=\"https://uploads.commoninja.com/searchengine/wordpress/sapo-feed.png\"/>\r\n"
				+ "                  </p>\r\n"
				+ "                  <h1  style=\"text-align: center; font-family: Archivo Narrow; font-weight: normal; margin: 0; margin-bottom: 16px;\">Cảm ơn bạn đã đặt hàng</h1>\r\n"
				+ "                  \r\n"
				+ "                  <p style=\"font-family: Archivo Narrow; font-size: 16px; font-weight: normal;text-align: center; margin: 0; margin-bottom: 16px;\"><h2 style=\"color:red; text-align: center;\"></h2></p>\r\n"
				+ "                  <p style=\"text-align: center;\">                  <a href=\""
				+ "" + link
				+ "\" target=\"_blank\" style=\"border: solid 2px #2AC37D; border-radius: 4px; box-sizing: border-box; cursor: pointer; display: inline-block; font-size: 16px; text-align: center; font-weight: bold; margin: 0; padding: 12px 24px; text-decoration: none; text-transform: capitalize; background-color: #2AC37D; border-color: #2AC37D; color: #ffffff;\">Đến trang chủ SAPO</a>\r\n"
				+ "                  </p>\r\n"
				+ "                  <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"btn btn-primary\" style=\"border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; box-sizing: border-box; width: 100%; min-width: 100%;\" width=\"100%\">\r\n"
				+ "\r\n"
				+ "                    <tbody>\r\n"
				+ "                      <tr>\r\n"
				+ "                        <td align=\"left\" style=\"font-family: Archivo Narrow; font-size: 16px; vertical-align: top; padding-bottom: 16px;\" valign=\"top\">\r\n"
				+ "                          <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: auto;\">\r\n"
				+ "                            <tbody>\r\n"
				+ "                              <tr>\r\n"
				+ "                                <td style=\"font-family: Archivo Narrow; font-size: 16px; vertical-align: top; border-radius: 4px; text-align: center; background-color: #0867ec;\" valign=\"top\" align=\"center\" bgcolor=\"#0867ec\">  </td>\r\n"
				+ "                              </tr>\r\n"
				+ "                            </tbody>\r\n"
				+ "                          </table>\r\n"
				+ "                        </td>\r\n"
				+ "                      </tr>\r\n"
				+ "                    </tbody>\r\n"
				+ "                  </table>\r\n"
				+ "                  <p style=\"text-align: center;font-family: Archivo Narrow; font-size: 16px; font-weight: normal; margin: 0; margin-bottom: 16px;\">Đơn hàng của bạn đã sẵn sàng để vận chuyển. Chúng tôi sẽ cho bạn biết ngay khi nó bắt đầu di chuyển đến vị trí của bạn</p>\r\n"
				+ "                  <p style=\"text-align: center;font-family: Archivo Narrow; font-size: 16px; font-weight: normal; margin: 0; margin-bottom: 16px;\">Cảm ơn bạn đã tin tưởng lựa chọn SAPO STORE</p>\r\n"
				+ "                  <p style=\"text-align: center;font-family: Archivo Narrow; font-size: 16px; font-weight: normal; margin: 0; margin-bottom: 16px;\">Trân trọng!</p>\r\n"
				+ "                </td>\r\n"
				+ "              </tr>\r\n"
				+ "\r\n"
				+ "              <!-- END MAIN CONTENT AREA -->\r\n"
				+ "              </table>\r\n"
				+ "\r\n"
				+ "            <!-- START FOOTER -->\r\n"
				+ "            <div class=\"footer\" style=\"clear: both; padding-top: 24px; text-align: center; width: 100%;\">\r\n"
				+ "              <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;\" width=\"100%\">\r\n"
				+ "                <tr>\r\n"
				+ "                  <td class=\"content-block\" style=\"font-family: Archivo Narrow; vertical-align: top; color: #9a9ea6; font-size: 16px; text-align: center;\" valign=\"top\" align=\"center\">\r\n"
				+ "                    <span class=\"apple-link\" style=\"color: #9a9ea6; font-size: 16px; text-align: center;\">87-89 Hồ Văn Huê, P9, Q.Phú Nhuận, TP.HCM</span>\r\n"
				+ "                    <br> Chăm sóc khách hàng: <a href=\"#\" style=\"text-decoration: underline; color: #9a9ea6; font-size: 16px; text-align: center;\"> cskh1@sapostore.com</a>.\r\n"
				+ "                  </td>\r\n"
				+ "                </tr>\r\n"
				+ "                <tr>\r\n"
				+ "                  <td class=\"content-block powered-by\" style=\"font-family: Archivo Narrow; vertical-align: top; color: #9a9ea6; font-size: 16px; text-align: center;\" valign=\"top\" align=\"center\">\r\n"
				+ "                    Bản quyền thuộc về <a href=\"#\" style=\"color: #9a9ea6; font-size: 16px; text-align: center; text-decoration: none;\">@ ABCXYZ123</a>\r\n"
				+ "                  </td>\r\n"
				+ "                </tr>\r\n"
				+ "              </table>\r\n"
				+ "            </div>\r\n"
				+ "          </div>\r\n"
				+ "        </td>\r\n"
				+ "        <td style=\"font-family: Archivo Narrow; font-size: 16px; vertical-align: top;\" valign=\"top\">&nbsp;</td>\r\n"
				+ "      </tr>\r\n"
				+ "    </table>\r\n"
				+ "  </body>\r\n"
				+ "</html>"
				+ "";
	}
}
